[package]
name = "terraprisma-installer"
edition = "2021"

version = "0.1.0"
authors = ["pbone"]
description = "Native installer for Terraprisma."
license-file = "../LICENSE"

[dependencies]
flate2 = "1.0.26"
regex = "1.9.0"
tar = "0.4.38"
ureq = "2.7.1"
which = "4.4.0"
zip-extract = "0.1.2"
